feat: Updated .github/workflows/main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,6 +5,18 @@ on:
     branches: [ main ]
 
 jobs:
+    check_cla_status:
+      runs-on: ubuntu-latest
+      if: github.event_name == 'pull_request'
+      steps:
+        - name: Check CLA Status
+          uses: cla-assistant/github-action@v2.1.3-beta
+          with:
+            pull-request: 1331
+        - name: Fail on CLA Status Failure
+          run: |
+            echo 'CLA status check failed'
+            exit 1
 
   build:
     runs-on: ubuntu-latest
